server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-service
              uri: lb://member-service
              predicates:
                - Path=/api/member/**
              filters:
                - StripPrefix=2
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/product/**
              filters:
                - StripPrefix=2
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=2
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payment/**
              filters:
                - StripPrefix=2
            - id: member-swagger
              uri: lb://member-service
              predicates:
                - Path=/member/swagger-ui/**, /member/v3/api-docs/**
              filters:
                - StripPrefix=1
            - id: order-swagger
              uri: lb://order-service
              predicates:
                - Path=/order/swagger-ui/**, /order/v3/api-docs/**
              filters:
                - StripPrefix=1
            - id: payment-swagger
              uri: lb://payment-service
              predicates:
                - Path=/payment/swagger-ui/**, /payment/v3/api-docs/**
              filters:
                - StripPrefix=1
            - id: webjars
              uri: lb://member-service
              predicates:
                - Path=/webjars/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET_KEY}

internal:
  secret: ${INTERNAL_SECRET_KEY}
