server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

internal:
  secret-key: ${INTERNAL_SECRET_KEY}

springdoc:
  override-server-url: ${GATEWAY_URL:http://localhost:8080}/api/payment
  swagger-ui:
    path: /swagger-ui/index.html
    config-url: /payment/v3/api-docs/swagger-config
    url: /payment/v3/api-docs
  api-docs:
    path: /v3/api-docs

payment:
  encryption:
    key: ${PAYMENT_ENCRYPTION_KEY}

toss:
  payments:
    client-key: ${TOSS_CLIENT_KEY}
    secret-key: ${TOSS_SECRET_KEY}
    confirm-url: https://api.tosspayments.com/v1/payments/confirm
    success-url: ${TOSS_SUCCESS_URL:http://localhost:8084/success.html}
    fail-url: ${TOSS_FAIL_URL:http://localhost:8084/fail.html}
