server:
  port: 8085

spring:
  application:
    name: settlement-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: settlement-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.notfound.settlement.adapter.in.kafka.dto"
        spring.json.value.default.type: "com.notfound.settlement.adapter.in.kafka.dto.PurchaseConfirmedEvent"
        spring.json.use.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

settlement:
  fee-rate: 0.03
  execution-day: 25
  batch:
    chunk-size: 100

internal:
  secret-key: ${INTERNAL_SECRET_KEY}

gateway:
  url: ${GATEWAY_URL:http://localhost:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    config-url: /settlement/v3/api-docs/swagger-config
    url: /settlement/v3/api-docs
  api-docs:
    path: /v3/api-docs
